### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by o0v0** [chanshiyucx/zero#4]
Failed to compile
./app/page.tsx:8:0
Module not found: Package path ./generated is not exported from package D:\boke\zero\node_modules\contentlayer (see exports field in D:\boke\zero\node_modules\contentlayer\package.json)
   6 | import AOS from 'aos'
   7 | import clsx from 'clsx'
>  8 | import { allPosts } from 'contentlayer/generated'
   9 | import { compareDesc, format } from 'date-fns'
  10 | import { Bookmark, Calendar, Tag } from 'lucide-react'
  11 | import { useRouter } from 'next/navigation'

https://nextjs.org/docs/messages/module-not-found
This error occurred during the build process and can only be dismissed by fixing the error.

瞧瞧看我使用 npm run dev  得到了什么内容

**Comment by o0v0** [comment]
D:\boke\zero>npm run dev

> zzz@1.0.0 dev
> next dev

Warning: Contentlayer might not work as expected on Windows
ConfigReadError (D:\boke\zero\contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'shiki' imported from D:\boke\zero\node_modules\rehype-pretty-code\dist\rehype-pretty-code.js
ConfigReadError (D:\boke\zero\contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'shiki' imported from D:\boke\zero\node_modules\rehype-pretty-code\dist\rehype-pretty-code.js
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 3.9s
 ○ Compiling /not-found ...
 ⨯ ./app/page.tsx:8:0
Module not found: Package path ./generated is not exported from package D:\boke\zero\node_modules\contentlayer (see exports field in D:\boke\zero\node_modules\contentlayer\package.json)
   6 | import AOS from 'aos'
   7 | import clsx from 'clsx'
>  8 | import { allPosts } from 'contentlayer/generated'
   9 | import { compareDesc, format } from 'date-fns'
  10 | import { Bookmark, Calendar, Tag } from 'lucide-react'
  11 | import { useRouter } from 'next/navigation'

https://nextjs.org/docs/messages/module-not-found
<w> [webpack.cache.PackFileCacheStrategy] Restoring pack failed from D:\boke\zero\.next\cache\webpack\client-development-fallback.pack.gz: Error: incorrect header check
<w> [webpack.cache.PackFileCacheStrategy] Restoring pack failed from D:\boke\zero\.next\cache\webpack\client-development-fallback.pack.gz: Error: incorrect header check

**Comment by o0v0** [comment]
D:\boke\zero>npm start

> zzz@1.0.0 start
> next start

[Error: ENOENT: no such file or directory, open 'D:\boke\zero\.next\BUILD_ID'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\boke\\zero\\.next\\BUILD_ID'
}

D:\boke\zero>

**Comment by chanshiyucx** [comment]
> Failed to compile ./app/page.tsx:8:0 Module not found: Package path ./generated is not exported from package D:\boke\zero\node_modules\contentlayer (see exports field in D:\boke\zero\node_modules\contentlayer\package.json) 6 | import AOS from 'aos' 7 | import clsx from 'clsx'
> 
> > 8 | import { allPosts } from 'contentlayer/generated'
> > 9 | import { compareDesc, format } from 'date-fns'
> > 10 | import { Bookmark, Calendar, Tag } from 'lucide-react'
> > 11 | import { useRouter } from 'next/navigation'
> 
> https://nextjs.org/docs/messages/module-not-found This error occurred during the build process and can only be dismissed by fixing the error.
> 
> 瞧瞧看我使用 npm run dev 得到了什么内容

contentlayer/generated 官方已经不维护了，坑有点多，已经打算换 [content-collection](https://www.content-collections.dev/) 了
